### ISSUE TITLE
Issue with your top down and bottom up understanding.

### ISSUE THREAD

**Issue by akashkinkarpandey** [arpanbasu1412/Dynamic-Programming#1]
The file named as `01KnapsackTopDown.cpp` has tabulated code written as `top down`.
But a code written in **tabulation format** is actually *bottom-up*.
And a code written in **memoized form** is *top-down*.
Kindly correct it.

**Comment by arpanbasu1412** [comment]
Thanks a lot brother @akashkinkarpandey 😃😎🤗
